// 
// Copyright (c) Microsoft.  All rights reserved.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//   http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// 
// See the License for the specific language governing permissions and
// limitations under the License.
// 

// Warning: This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if the
// code is regenerated.

package com.microsoft.windowsazure.management.models;

import com.microsoft.windowsazure.OperationResponse;
import com.microsoft.windowsazure.management.models.AffinityGroupGetResponse.HostedServiceReference;
import com.microsoft.windowsazure.management.models.AffinityGroupGetResponse.StorageServiceReference;
import java.net.URI;
import java.util.ArrayList;

/**
* The Get Affinity Group operation response.
*/
public class AffinityGroupGetResponse extends OperationResponse
{
    private ArrayList<String> _capabilities;
    
    /**
    * Indicates if the virtual machine related operations can be performed in
    * this affinity group. If so, the string PersistentVMRole will be returned
    * by this element. Otherwise, this element will not be present.
    */
    public ArrayList<String> getCapabilities() { return this._capabilities; }
    
    /**
    * Indicates if the virtual machine related operations can be performed in
    * this affinity group. If so, the string PersistentVMRole will be returned
    * by this element. Otherwise, this element will not be present.
    */
    public void setCapabilities(ArrayList<String> capabilities) { this._capabilities = capabilities; }
    
    private String _description;
    
    /**
    * The user supplied description of this affinity group.
    */
    public String getDescription() { return this._description; }
    
    /**
    * The user supplied description of this affinity group.
    */
    public void setDescription(String description) { this._description = description; }
    
    private ArrayList<AffinityGroupGetResponse.HostedServiceReference> _hostedServices;
    
    /**
    * The hosted services associated with this affinity group.
    */
    public ArrayList<AffinityGroupGetResponse.HostedServiceReference> getHostedServices() { return this._hostedServices; }
    
    /**
    * The hosted services associated with this affinity group.
    */
    public void setHostedServices(ArrayList<AffinityGroupGetResponse.HostedServiceReference> hostedServices) { this._hostedServices = hostedServices; }
    
    private String _label;
    
    /**
    * The user supplied label of the affinity group returned as a base-64
    * encoded string.
    */
    public String getLabel() { return this._label; }
    
    /**
    * The user supplied label of the affinity group returned as a base-64
    * encoded string.
    */
    public void setLabel(String label) { this._label = label; }
    
    private String _location;
    
    /**
    * The location of the data center that the affinity group is associated
    * with.
    */
    public String getLocation() { return this._location; }
    
    /**
    * The location of the data center that the affinity group is associated
    * with.
    */
    public void setLocation(String location) { this._location = location; }
    
    private String _name;
    
    /**
    * The user supplied name of the affinity group.
    */
    public String getName() { return this._name; }
    
    /**
    * The user supplied name of the affinity group.
    */
    public void setName(String name) { this._name = name; }
    
    private ArrayList<AffinityGroupGetResponse.StorageServiceReference> _storageServices;
    
    /**
    * The storage services associated with this affinity group.
    */
    public ArrayList<AffinityGroupGetResponse.StorageServiceReference> getStorageServices() { return this._storageServices; }
    
    /**
    * The storage services associated with this affinity group.
    */
    public void setStorageServices(ArrayList<AffinityGroupGetResponse.StorageServiceReference> storageServices) { this._storageServices = storageServices; }
    
    /**
    * Initializes a new instance of the AffinityGroupGetResponse class.
    *
    */
    public AffinityGroupGetResponse()
    {
        this._capabilities = new ArrayList<String>();
        this._hostedServices = new ArrayList<AffinityGroupGetResponse.HostedServiceReference>();
        this._storageServices = new ArrayList<AffinityGroupGetResponse.StorageServiceReference>();
    }
    
    /**
    * Reference to a hosted service associated with an affinity group.
    */
    public class HostedServiceReference
    {
        private String _serviceName;
        
        /**
        * The name of the hosted service.
        */
        public String getServiceName() { return this._serviceName; }
        
        /**
        * The name of the hosted service.
        */
        public void setServiceName(String serviceName) { this._serviceName = serviceName; }
        
        private URI _uri;
        
        /**
        * The Service Management API request URI used to perform Get Hosted
        * Service Properties requests against the hosted service.
        */
        public URI getUri() { return this._uri; }
        
        /**
        * The Service Management API request URI used to perform Get Hosted
        * Service Properties requests against the hosted service.
        */
        public void setUri(URI uri) { this._uri = uri; }
        
        /**
        * Initializes a new instance of the HostedServiceReference class.
        *
        */
        public HostedServiceReference()
        {
        }
    }
    
    /**
    * Reference to a storage service associated with an affinity group.
    */
    public class StorageServiceReference
    {
        private String _serviceName;
        
        /**
        * The user supplied name of the storage account.
        */
        public String getServiceName() { return this._serviceName; }
        
        /**
        * The user supplied name of the storage account.
        */
        public void setServiceName(String serviceName) { this._serviceName = serviceName; }
        
        private URI _uri;
        
        /**
        * The Service Management API request URI used to perform Get Storage
        * Account Properties requests against the storage account.
        */
        public URI getUri() { return this._uri; }
        
        /**
        * The Service Management API request URI used to perform Get Storage
        * Account Properties requests against the storage account.
        */
        public void setUri(URI uri) { this._uri = uri; }
        
        /**
        * Initializes a new instance of the StorageServiceReference class.
        *
        */
        public StorageServiceReference()
        {
        }
    }
}
