// 
// Copyright (c) Microsoft.  All rights reserved.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//   http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// 
// See the License for the specific language governing permissions and
// limitations under the License.
// 

// Warning: This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if the
// code is regenerated.

package com.microsoft.windowsazure.management.models;

import com.microsoft.windowsazure.OperationResponse;
import com.microsoft.windowsazure.management.models.ManagementCertificateListResponse.SubscriptionCertificate;
import java.lang.Iterable;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;

/**
* The List Management Certificates operation response.
*/
public class ManagementCertificateListResponse extends OperationResponse implements Iterable<ManagementCertificateListResponse.SubscriptionCertificate>
{
    private ArrayList<ManagementCertificateListResponse.SubscriptionCertificate> _subscriptionCertificates;
    
    /**
    * The management certificates that are valid for your subscription.
    */
    public ArrayList<ManagementCertificateListResponse.SubscriptionCertificate> getSubscriptionCertificates() { return this._subscriptionCertificates; }
    
    /**
    * The management certificates that are valid for your subscription.
    */
    public void setSubscriptionCertificates(ArrayList<ManagementCertificateListResponse.SubscriptionCertificate> subscriptionCertificates) { this._subscriptionCertificates = subscriptionCertificates; }
    
    /**
    * Initializes a new instance of the ManagementCertificateListResponse class.
    *
    */
    public ManagementCertificateListResponse()
    {
        this._subscriptionCertificates = new ArrayList<ManagementCertificateListResponse.SubscriptionCertificate>();
    }
    
    /**
    * Gets the sequence of SubscriptionCertificates.
    *
    */
    public Iterator<ManagementCertificateListResponse.SubscriptionCertificate> iterator()
    {
        return this.getSubscriptionCertificates().iterator();
    }
    
    /**
    * A management certificate that is valid for your subscription.
    */
    public class SubscriptionCertificate
    {
        private Date _created;
        
        /**
        * The time that the management certificate was created, in UTC.
        */
        public Date getCreated() { return this._created; }
        
        /**
        * The time that the management certificate was created, in UTC.
        */
        public void setCreated(Date created) { this._created = created; }
        
        private byte[] _data;
        
        /**
        * A base64 representation of the data contained in the management
        * certificate, in .cer format.
        */
        public byte[] getData() { return this._data; }
        
        /**
        * A base64 representation of the data contained in the management
        * certificate, in .cer format.
        */
        public void setData(byte[] data) { this._data = data; }
        
        private byte[] _publicKey;
        
        /**
        * A base64 representation of the management certificate public key.
        */
        public byte[] getPublicKey() { return this._publicKey; }
        
        /**
        * A base64 representation of the management certificate public key.
        */
        public void setPublicKey(byte[] publicKey) { this._publicKey = publicKey; }
        
        private String _thumbprint;
        
        /**
        * The X509 certificate thumb print property of the management
        * certificate. This thumb print uniquely identifies the certificate.
        */
        public String getThumbprint() { return this._thumbprint; }
        
        /**
        * The X509 certificate thumb print property of the management
        * certificate. This thumb print uniquely identifies the certificate.
        */
        public void setThumbprint(String thumbprint) { this._thumbprint = thumbprint; }
        
        /**
        * Initializes a new instance of the SubscriptionCertificate class.
        *
        */
        public SubscriptionCertificate()
        {
        }
    }
}
