// 
// Copyright (c) Microsoft.  All rights reserved.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//   http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// 
// See the License for the specific language governing permissions and
// limitations under the License.
// 

// Warning: This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if the
// code is regenerated.

package com.microsoft.windowsazure.management.models;

import com.microsoft.windowsazure.OperationResponse;
import com.microsoft.windowsazure.management.models.SubscriptionStatus;

/**
* The Get Subscription operation response.
*/
public class SubscriptionGetResponse extends OperationResponse
{
    private String _accountAdminLiveEmailId;
    
    /**
    * The live ID of the account administrator.
    */
    public String getAccountAdminLiveEmailId() { return this._accountAdminLiveEmailId; }
    
    /**
    * The live ID of the account administrator.
    */
    public void setAccountAdminLiveEmailId(String accountAdminLiveEmailId) { this._accountAdminLiveEmailId = accountAdminLiveEmailId; }
    
    private int _currentCoreCount;
    
    /**
    * The number of currently allocated cores.
    */
    public int getCurrentCoreCount() { return this._currentCoreCount; }
    
    /**
    * The number of currently allocated cores.
    */
    public void setCurrentCoreCount(int currentCoreCount) { this._currentCoreCount = currentCoreCount; }
    
    private int _currentDnsServers;
    
    /**
    * The current number of DNS servers allocated on this subscription.
    */
    public int getCurrentDnsServers() { return this._currentDnsServers; }
    
    /**
    * The current number of DNS servers allocated on this subscription.
    */
    public void setCurrentDnsServers(int currentDnsServers) { this._currentDnsServers = currentDnsServers; }
    
    private int _currentHostedServices;
    
    /**
    * The number of currently allocated cloud services.
    */
    public int getCurrentHostedServices() { return this._currentHostedServices; }
    
    /**
    * The number of currently allocated cloud services.
    */
    public void setCurrentHostedServices(int currentHostedServices) { this._currentHostedServices = currentHostedServices; }
    
    private int _currentLocalNetworkSites;
    
    /**
    * The current number of local virtual network sites that are allocated on
    * this subscription.
    */
    public int getCurrentLocalNetworkSites() { return this._currentLocalNetworkSites; }
    
    /**
    * The current number of local virtual network sites that are allocated on
    * this subscription.
    */
    public void setCurrentLocalNetworkSites(int currentLocalNetworkSites) { this._currentLocalNetworkSites = currentLocalNetworkSites; }
    
    private int _currentStorageAccounts;
    
    /**
    * The number of currently allocated storage accounts.
    */
    public int getCurrentStorageAccounts() { return this._currentStorageAccounts; }
    
    /**
    * The number of currently allocated storage accounts.
    */
    public void setCurrentStorageAccounts(int currentStorageAccounts) { this._currentStorageAccounts = currentStorageAccounts; }
    
    private int _currentVirtualNetworkSites;
    
    /**
    * The number of currently allocated virtual network sites.
    */
    public int getCurrentVirtualNetworkSites() { return this._currentVirtualNetworkSites; }
    
    /**
    * The number of currently allocated virtual network sites.
    */
    public void setCurrentVirtualNetworkSites(int currentVirtualNetworkSites) { this._currentVirtualNetworkSites = currentVirtualNetworkSites; }
    
    private int _maximumCoreCount;
    
    /**
    * The maximum number of cores that can be allocated on this subscription.
    */
    public int getMaximumCoreCount() { return this._maximumCoreCount; }
    
    /**
    * The maximum number of cores that can be allocated on this subscription.
    */
    public void setMaximumCoreCount(int maximumCoreCount) { this._maximumCoreCount = maximumCoreCount; }
    
    private int _maximumDnsServers;
    
    /**
    * The maximum number of DNS servers that can be allocated on this
    * subscription.
    */
    public int getMaximumDnsServers() { return this._maximumDnsServers; }
    
    /**
    * The maximum number of DNS servers that can be allocated on this
    * subscription.
    */
    public void setMaximumDnsServers(int maximumDnsServers) { this._maximumDnsServers = maximumDnsServers; }
    
    private int _maximumHostedServices;
    
    /**
    * The maximum number of cloud services that can be allocated on this
    * subscription.
    */
    public int getMaximumHostedServices() { return this._maximumHostedServices; }
    
    /**
    * The maximum number of cloud services that can be allocated on this
    * subscription.
    */
    public void setMaximumHostedServices(int maximumHostedServices) { this._maximumHostedServices = maximumHostedServices; }
    
    private int _maximumLocalNetworkSites;
    
    /**
    * The maximum number of local virtual network sites that can be allocated
    * on this subscription.
    */
    public int getMaximumLocalNetworkSites() { return this._maximumLocalNetworkSites; }
    
    /**
    * The maximum number of local virtual network sites that can be allocated
    * on this subscription.
    */
    public void setMaximumLocalNetworkSites(int maximumLocalNetworkSites) { this._maximumLocalNetworkSites = maximumLocalNetworkSites; }
    
    private int _maximumStorageAccounts;
    
    /**
    * The maximum number of storage accounts that can be allocated on this
    * subscription.
    */
    public int getMaximumStorageAccounts() { return this._maximumStorageAccounts; }
    
    /**
    * The maximum number of storage accounts that can be allocated on this
    * subscription.
    */
    public void setMaximumStorageAccounts(int maximumStorageAccounts) { this._maximumStorageAccounts = maximumStorageAccounts; }
    
    private int _maximumVirtualNetworkSites;
    
    /**
    * The maximum number of virtual network sites that can be allocated on this
    * subscription.
    */
    public int getMaximumVirtualNetworkSites() { return this._maximumVirtualNetworkSites; }
    
    /**
    * The maximum number of virtual network sites that can be allocated on this
    * subscription.
    */
    public void setMaximumVirtualNetworkSites(int maximumVirtualNetworkSites) { this._maximumVirtualNetworkSites = maximumVirtualNetworkSites; }
    
    private String _serviceAdminLiveEmailId;
    
    /**
    * The live ID of the subscription administrator.
    */
    public String getServiceAdminLiveEmailId() { return this._serviceAdminLiveEmailId; }
    
    /**
    * The live ID of the subscription administrator.
    */
    public void setServiceAdminLiveEmailId(String serviceAdminLiveEmailId) { this._serviceAdminLiveEmailId = serviceAdminLiveEmailId; }
    
    private String _subscriptionID;
    
    /**
    * The subscription ID that the operation was called on.
    */
    public String getSubscriptionID() { return this._subscriptionID; }
    
    /**
    * The subscription ID that the operation was called on.
    */
    public void setSubscriptionID(String subscriptionID) { this._subscriptionID = subscriptionID; }
    
    private String _subscriptionName;
    
    /**
    * The user-supplied name of the subscription.
    */
    public String getSubscriptionName() { return this._subscriptionName; }
    
    /**
    * The user-supplied name of the subscription.
    */
    public void setSubscriptionName(String subscriptionName) { this._subscriptionName = subscriptionName; }
    
    private SubscriptionStatus _subscriptionStatus;
    
    /**
    * The subscription status.
    */
    public SubscriptionStatus getSubscriptionStatus() { return this._subscriptionStatus; }
    
    /**
    * The subscription status.
    */
    public void setSubscriptionStatus(SubscriptionStatus subscriptionStatus) { this._subscriptionStatus = subscriptionStatus; }
    
    /**
    * Initializes a new instance of the SubscriptionGetResponse class.
    *
    */
    public SubscriptionGetResponse()
    {
    }
}
