// 
// Copyright (c) Microsoft.  All rights reserved.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//   http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// 
// See the License for the specific language governing permissions and
// limitations under the License.
// 

// Warning: This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if the
// code is regenerated.

package com.microsoft.windowsazure.management;

import com.microsoft.windowsazure.OperationResponse;
import com.microsoft.windowsazure.management.ManagementCertificateOperations;
import com.microsoft.windowsazure.management.ManagementClientImpl;
import com.microsoft.windowsazure.management.models.ManagementCertificateCreateParameters;
import com.microsoft.windowsazure.management.models.ManagementCertificateGetResponse;
import com.microsoft.windowsazure.management.models.ManagementCertificateListResponse;
import com.microsoft.windowsazure.management.models.ManagementCertificateListResponse.SubscriptionCertificate;
import com.microsoft.windowsazure.services.core.CloudException;
import com.microsoft.windowsazure.services.core.ServiceOperations;
import java.io.IOException;
import java.io.StringWriter;
import java.io.UnsupportedEncodingException;
import java.net.URISyntaxException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.apache.commons.codec.binary.Base64;
import org.apache.http.HttpResponse;
import org.apache.http.client.methods.HttpDelete;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.entity.StringEntity;
import org.apache.http.impl.nio.client.CloseableHttpAsyncClient;
import org.apache.http.impl.nio.client.HttpAsyncClients;
import org.apache.http.util.EntityUtils;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;

/**
* You can use management certificates, which are also known as subscription
* certificates, to authenticate clients attempting to connect to resources
* associated with your Windows Azure subscription.  (see
* http://msdn.microsoft.com/en-us/library/windowsazure/jj154124.aspx for more
* information)
*/
public class ManagementCertificateOperationsImpl implements ServiceOperations<ManagementClientImpl>, ManagementCertificateOperations
{
    private ExecutorService _executorService;
    
    public ExecutorService getExecutorService() { return this._executorService; }
    
    /**
    * Initializes a new instance of the ManagementCertificateOperationsImpl
    * class.
    *
    * @param client Reference to the service client.
    */
    ManagementCertificateOperationsImpl(ManagementClientImpl client)
    {
        this._client = client;
        this._executorService = Executors.newCachedThreadPool();
    }
    
    private ManagementClientImpl _client;
    
    /**
    * Gets a reference to the
    * microsoft.windowsazure.management.ManagementClientImpl.
    */
    public ManagementClientImpl getClient() { return this._client; }
    
    /**
    * The Add Management Certificate operation adds a certificate to the list
    * of management certificates. Management certificates, which are also
    * known as subscription certificates, authenticate clients attempting to
    * connect to resources associated with your Windows Azure subscription.
    * (see http://msdn.microsoft.com/en-us/library/windowsazure/jj154123.aspx
    * for more information)
    *
    * @param parameters Parameters supplied to the Create Management
    * Certificate operation.
    * @return A standard service response including an HTTP status code and
    * request ID.
    */
    @Override
    public Future<OperationResponse> createAsync(final ManagementCertificateCreateParameters parameters)
    {
        return this.getExecutorService().submit(new Callable<OperationResponse>() { @Override
        public OperationResponse call() throws Exception, Exception
        {
            return create(parameters);
        }
         });
    }
    
    /**
    * The Add Management Certificate operation adds a certificate to the list
    * of management certificates. Management certificates, which are also
    * known as subscription certificates, authenticate clients attempting to
    * connect to resources associated with your Windows Azure subscription.
    * (see http://msdn.microsoft.com/en-us/library/windowsazure/jj154123.aspx
    * for more information)
    *
    * @param parameters Parameters supplied to the Create Management
    * Certificate operation.
    * @return A standard service response including an HTTP status code and
    * request ID.
    */
    @Override
    public OperationResponse create(ManagementCertificateCreateParameters parameters) throws ParserConfigurationException, SAXException, TransformerConfigurationException, TransformerException, UnsupportedEncodingException, InterruptedException, ExecutionException, CloudException, IOException, ParserConfigurationException, SAXException, TransformerConfigurationException, TransformerException, UnsupportedEncodingException, InterruptedException, ExecutionException, CloudException, IOException
    {
        // Validate
        if (parameters == null)
        {
            throw new NullPointerException("parameters");
        }
        
        // Tracing
        
        // Construct URL
        String url = this.getClient().getBaseUri() + "/" + this.getClient().getCredentials().getSubscriptionId() + "/certificates";
        
        // Create HTTP transport objects
        CloseableHttpAsyncClient httpClient = HttpAsyncClients.createDefault();
        try
        {
            httpClient.start();
            HttpPost httpRequest = new HttpPost(url);
            
            // Set Headers
            httpRequest.setHeader("Content-Type", "application/xml");
            httpRequest.setHeader("x-ms-version", "2013-03-01");
            
            // Set Credentials
            
            // Serialize Request
            String requestContent = null;
            DocumentBuilderFactory documentBuilderFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder documentBuilder = documentBuilderFactory.newDocumentBuilder();
            Document requestDoc = documentBuilder.newDocument();
            
            Element subscriptionCertificateElement = requestDoc.createElementNS("http://schemas.microsoft.com/windowsazure", "SubscriptionCertificate");
            requestDoc.appendChild(subscriptionCertificateElement);
            
            if (parameters.getPublicKey() != null)
            {
                Element subscriptionCertificatePublicKeyElement = requestDoc.createElementNS("http://schemas.microsoft.com/windowsazure", "SubscriptionCertificatePublicKey");
                subscriptionCertificatePublicKeyElement.appendChild(requestDoc.createTextNode(new String(Base64.encodeBase64(parameters.getPublicKey()))));
                subscriptionCertificateElement.appendChild(subscriptionCertificatePublicKeyElement);
            }
            
            if (parameters.getThumbprint() != null)
            {
                Element subscriptionCertificateThumbprintElement = requestDoc.createElementNS("http://schemas.microsoft.com/windowsazure", "SubscriptionCertificateThumbprint");
                subscriptionCertificateThumbprintElement.appendChild(requestDoc.createTextNode(parameters.getThumbprint()));
                subscriptionCertificateElement.appendChild(subscriptionCertificateThumbprintElement);
            }
            
            if (parameters.getData() != null)
            {
                Element subscriptionCertificateDataElement = requestDoc.createElementNS("http://schemas.microsoft.com/windowsazure", "SubscriptionCertificateData");
                subscriptionCertificateDataElement.appendChild(requestDoc.createTextNode(new String(Base64.encodeBase64(parameters.getData()))));
                subscriptionCertificateElement.appendChild(subscriptionCertificateDataElement);
            }
            
            DOMSource domSource = new DOMSource(requestDoc);
            StreamResult streamResult = new StreamResult(new StringWriter());
            TransformerFactory transformerFactory = TransformerFactory.newInstance();
            Transformer transformer = transformerFactory.newTransformer();
            transformer.transform(domSource, streamResult);
            requestContent = requestDoc.toString();
            StringEntity entity = new StringEntity(requestContent);
            httpRequest.setEntity(entity);
            httpRequest.setHeader("Content-Type", "application/xml");
            
            // Send Request
            HttpResponse httpResponse = null;
            Future<HttpResponse> httpRequestFuture = httpClient.execute(httpRequest, null);
            httpResponse = httpRequestFuture.get();
            int statusCode = httpResponse.getStatusLine().getStatusCode();
            if (statusCode != 200)
            {
                CloudException ex = CloudException.createFromXml(httpRequest, requestContent, httpResponse, EntityUtils.toString(httpResponse.getEntity()));
                throw ex;
            }
            
            // Create Result
            OperationResponse result = new OperationResponse();
            result.setStatusCode(statusCode);
            if (httpResponse.getHeaders("x-ms-request-id").length > 0)
            {
                result.setRequestId(httpResponse.getFirstHeader("x-ms-request-id").getValue());
            }
            
            return result;
        }
        finally
        {
            if (httpClient != null)
            {
                httpClient.close();
            }
        }
    }
    
    /**
    * The Delete Management Certificate operation deletes a certificate from
    * the list of management certificates. Management certificates, which are
    * also known as subscription certificates, authenticate clients attempting
    * to connect to resources associated with your Windows Azure subscription.
    * (see http://msdn.microsoft.com/en-us/library/windowsazure/jj154127.aspx
    * for more information)
    *
    * @param thumbprint the thumbprint value of the certificate to delete.
    * @return A standard service response including an HTTP status code and
    * request ID.
    */
    @Override
    public Future<OperationResponse> deleteAsync(final String thumbprint)
    {
        return this.getExecutorService().submit(new Callable<OperationResponse>() { @Override
        public OperationResponse call() throws Exception, Exception
        {
            return delete(thumbprint);
        }
         });
    }
    
    /**
    * The Delete Management Certificate operation deletes a certificate from
    * the list of management certificates. Management certificates, which are
    * also known as subscription certificates, authenticate clients attempting
    * to connect to resources associated with your Windows Azure subscription.
    * (see http://msdn.microsoft.com/en-us/library/windowsazure/jj154127.aspx
    * for more information)
    *
    * @param thumbprint the thumbprint value of the certificate to delete.
    * @return A standard service response including an HTTP status code and
    * request ID.
    */
    @Override
    public OperationResponse delete(String thumbprint) throws InterruptedException, ExecutionException, CloudException, IOException, InterruptedException, ExecutionException, CloudException, IOException
    {
        // Validate
        if (thumbprint == null)
        {
            throw new NullPointerException("thumbprint");
        }
        
        // Tracing
        
        // Construct URL
        String url = this.getClient().getBaseUri() + "/" + this.getClient().getCredentials().getSubscriptionId() + "/certificates/" + thumbprint;
        
        // Create HTTP transport objects
        CloseableHttpAsyncClient httpClient = HttpAsyncClients.createDefault();
        try
        {
            httpClient.start();
            HttpDelete httpRequest = new HttpDelete(url);
            
            // Set Headers
            httpRequest.setHeader("x-ms-version", "2013-03-01");
            
            // Set Credentials
            
            // Send Request
            HttpResponse httpResponse = null;
            Future<HttpResponse> httpRequestFuture = httpClient.execute(httpRequest, null);
            httpResponse = httpRequestFuture.get();
            int statusCode = httpResponse.getStatusLine().getStatusCode();
            if (statusCode != 200 && statusCode != 404)
            {
                CloudException ex = CloudException.createFromXml(httpRequest, null, httpResponse, EntityUtils.toString(httpResponse.getEntity()));
                throw ex;
            }
            
            // Create Result
            OperationResponse result = new OperationResponse();
            result.setStatusCode(statusCode);
            if (httpResponse.getHeaders("x-ms-request-id").length > 0)
            {
                result.setRequestId(httpResponse.getFirstHeader("x-ms-request-id").getValue());
            }
            
            return result;
        }
        finally
        {
            if (httpClient != null)
            {
                httpClient.close();
            }
        }
    }
    
    /**
    * The Get Management Certificate operation retrieves information about the
    * management certificate with the specified thumbprint. Management
    * certificates, which are also known as subscription certificates,
    * authenticate clients attempting to connect to resources associated with
    * your Windows Azure subscription.  (see
    * http://msdn.microsoft.com/en-us/library/windowsazure/jj154131.aspx for
    * more information)
    *
    * @param thumbprint The thumbprint value of the certificate to retrieve
    * information about.
    * @return The Get Management Certificate operation response.
    */
    @Override
    public Future<ManagementCertificateGetResponse> getAsync(final String thumbprint)
    {
        return this.getExecutorService().submit(new Callable<ManagementCertificateGetResponse>() { @Override
        public ManagementCertificateGetResponse call() throws Exception, Exception
        {
            return get(thumbprint);
        }
         });
    }
    
    /**
    * The Get Management Certificate operation retrieves information about the
    * management certificate with the specified thumbprint. Management
    * certificates, which are also known as subscription certificates,
    * authenticate clients attempting to connect to resources associated with
    * your Windows Azure subscription.  (see
    * http://msdn.microsoft.com/en-us/library/windowsazure/jj154131.aspx for
    * more information)
    *
    * @param thumbprint The thumbprint value of the certificate to retrieve
    * information about.
    * @return The Get Management Certificate operation response.
    */
    @Override
    public ManagementCertificateGetResponse get(String thumbprint) throws InterruptedException, ExecutionException, CloudException, ParserConfigurationException, SAXException, IOException, URISyntaxException, InterruptedException, ExecutionException, CloudException, ParserConfigurationException, SAXException, IOException, ParseException, IOException
    {
        // Validate
        if (thumbprint == null)
        {
            throw new NullPointerException("thumbprint");
        }
        
        // Tracing
        
        // Construct URL
        String url = this.getClient().getBaseUri() + "/" + this.getClient().getCredentials().getSubscriptionId() + "/certificates/" + thumbprint;
        
        // Create HTTP transport objects
        CloseableHttpAsyncClient httpClient = HttpAsyncClients.createDefault();
        try
        {
            httpClient.start();
            HttpGet httpRequest = new HttpGet(url);
            
            // Set Headers
            httpRequest.setHeader("x-ms-version", "2013-03-01");
            
            // Set Credentials
            
            // Send Request
            HttpResponse httpResponse = null;
            Future<HttpResponse> httpRequestFuture = httpClient.execute(httpRequest, null);
            httpResponse = httpRequestFuture.get();
            int statusCode = httpResponse.getStatusLine().getStatusCode();
            if (statusCode != 200)
            {
                CloudException ex = CloudException.createFromXml(httpRequest, null, httpResponse, EntityUtils.toString(httpResponse.getEntity()));
                throw ex;
            }
            
            // Create Result
            ManagementCertificateGetResponse result = new ManagementCertificateGetResponse();
            result.setStatusCode(statusCode);
            if (httpResponse.getHeaders("x-ms-request-id").length > 0)
            {
                result.setRequestId(httpResponse.getFirstHeader("x-ms-request-id").getValue());
            }
            
            // Deserialize Response
            String responseContent = EntityUtils.toString(httpResponse.getEntity());
            DocumentBuilderFactory documentBuilderFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder documentBuilder = documentBuilderFactory.newDocumentBuilder();
            Document responseDoc = documentBuilder.parse(responseContent);
            
            NodeList elements = responseDoc.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "SubscriptionCertificate");
            Element subscriptionCertificateElement = elements.getLength() > 0 ? ((Element)elements.item(0)) : null;
            if (subscriptionCertificateElement != null)
            {
                NodeList elements2 = subscriptionCertificateElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "SubscriptionCertificatePublicKey");
                Element subscriptionCertificatePublicKeyElement = elements2.getLength() > 0 ? ((Element)elements2.item(0)) : null;
                if (subscriptionCertificatePublicKeyElement != null)
                {
                    byte[] subscriptionCertificatePublicKeyInstance;
                    subscriptionCertificatePublicKeyInstance = Base64.decodeBase64(subscriptionCertificatePublicKeyElement.getNodeValue().getBytes());
                    result.setPublicKey(subscriptionCertificatePublicKeyInstance);
                }
                
                NodeList elements3 = subscriptionCertificateElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "SubscriptionCertificateThumbprint");
                Element subscriptionCertificateThumbprintElement = elements3.getLength() > 0 ? ((Element)elements3.item(0)) : null;
                if (subscriptionCertificateThumbprintElement != null)
                {
                    String subscriptionCertificateThumbprintInstance;
                    subscriptionCertificateThumbprintInstance = subscriptionCertificateThumbprintElement.getNodeValue();
                    result.setThumbprint(subscriptionCertificateThumbprintInstance);
                }
                
                NodeList elements4 = subscriptionCertificateElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "SubscriptionCertificateData");
                Element subscriptionCertificateDataElement = elements4.getLength() > 0 ? ((Element)elements4.item(0)) : null;
                if (subscriptionCertificateDataElement != null)
                {
                    byte[] subscriptionCertificateDataInstance;
                    subscriptionCertificateDataInstance = Base64.decodeBase64(subscriptionCertificateDataElement.getNodeValue().getBytes());
                    result.setData(subscriptionCertificateDataInstance);
                }
                
                NodeList elements5 = subscriptionCertificateElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "Created");
                Element createdElement = elements5.getLength() > 0 ? ((Element)elements5.item(0)) : null;
                if (createdElement != null)
                {
                    Calendar createdInstance;
                    SimpleDateFormat simpleDateFormat = new SimpleDateFormat("EEE MMM dd HH:mm:ss z yyyy");
                    Calendar calendar = Calendar.getInstance();
                    calendar.setTime(simpleDateFormat.parse(createdElement.getNodeValue()));
                    createdInstance = calendar;
                    result.setCreated(createdInstance);
                }
            }
            
            return result;
        }
        finally
        {
            if (httpClient != null)
            {
                httpClient.close();
            }
        }
    }
    
    /**
    * The List Management Certificates operation lists and returns basic
    * information about all of the management certificates associated with the
    * specified subscription. Management certificates, which are also known as
    * subscription certificates, authenticate clients attempting to connect to
    * resources associated with your Windows Azure subscription.  (see
    * http://msdn.microsoft.com/en-us/library/windowsazure/jj154105.aspx for
    * more information)
    *
    * @return The List Management Certificates operation response.
    */
    @Override
    public Future<ManagementCertificateListResponse> listAsync()
    {
        return this.getExecutorService().submit(new Callable<ManagementCertificateListResponse>() { @Override
        public ManagementCertificateListResponse call() throws Exception, Exception
        {
            return list();
        }
         });
    }
    
    /**
    * The List Management Certificates operation lists and returns basic
    * information about all of the management certificates associated with the
    * specified subscription. Management certificates, which are also known as
    * subscription certificates, authenticate clients attempting to connect to
    * resources associated with your Windows Azure subscription.  (see
    * http://msdn.microsoft.com/en-us/library/windowsazure/jj154105.aspx for
    * more information)
    *
    * @return The List Management Certificates operation response.
    */
    @Override
    public ManagementCertificateListResponse list() throws InterruptedException, ExecutionException, CloudException, ParserConfigurationException, SAXException, IOException, InterruptedException, ExecutionException, CloudException, ParserConfigurationException, SAXException, IOException, ParseException, IOException
    {
        // Validate
        
        // Tracing
        
        // Construct URL
        String url = this.getClient().getBaseUri() + "/" + this.getClient().getCredentials().getSubscriptionId() + "/certificates";
        
        // Create HTTP transport objects
        CloseableHttpAsyncClient httpClient = HttpAsyncClients.createDefault();
        try
        {
            httpClient.start();
            HttpGet httpRequest = new HttpGet(url);
            
            // Set Headers
            httpRequest.setHeader("x-ms-version", "2013-03-01");
            
            // Set Credentials
            
            // Send Request
            HttpResponse httpResponse = null;
            Future<HttpResponse> httpRequestFuture = httpClient.execute(httpRequest, null);
            httpResponse = httpRequestFuture.get();
            int statusCode = httpResponse.getStatusLine().getStatusCode();
            if (statusCode != 200)
            {
                CloudException ex = CloudException.createFromXml(httpRequest, null, httpResponse, EntityUtils.toString(httpResponse.getEntity()));
                throw ex;
            }
            
            // Create Result
            ManagementCertificateListResponse result = new ManagementCertificateListResponse();
            result.setStatusCode(statusCode);
            if (httpResponse.getHeaders("x-ms-request-id").length > 0)
            {
                result.setRequestId(httpResponse.getFirstHeader("x-ms-request-id").getValue());
            }
            
            // Deserialize Response
            String responseContent = EntityUtils.toString(httpResponse.getEntity());
            DocumentBuilderFactory documentBuilderFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder documentBuilder = documentBuilderFactory.newDocumentBuilder();
            Document responseDoc = documentBuilder.parse(responseContent);
            
            NodeList elements = responseDoc.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "SubscriptionCertificates");
            Element subscriptionCertificatesSequenceElement = elements.getLength() > 0 ? ((Element)elements.item(0)) : null;
            if (subscriptionCertificatesSequenceElement != null)
            {
                for (int i1 = 0; i1 < subscriptionCertificatesSequenceElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "SubscriptionCertificate").getLength(); i1 = i1 + 1)
                {
                    org.w3c.dom.Element subscriptionCertificatesElement = ((org.w3c.dom.Element)subscriptionCertificatesSequenceElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "SubscriptionCertificate").item(i1));
                    ManagementCertificateListResponse.SubscriptionCertificate subscriptionCertificateInstance = new ManagementCertificateListResponse.SubscriptionCertificate();
                    result.getSubscriptionCertificates().add(subscriptionCertificateInstance);
                    
                    NodeList elements2 = subscriptionCertificatesElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "SubscriptionCertificatePublicKey");
                    Element subscriptionCertificatePublicKeyElement = elements2.getLength() > 0 ? ((Element)elements2.item(0)) : null;
                    if (subscriptionCertificatePublicKeyElement != null)
                    {
                        byte[] subscriptionCertificatePublicKeyInstance;
                        subscriptionCertificatePublicKeyInstance = Base64.decodeBase64(subscriptionCertificatePublicKeyElement.getNodeValue().getBytes());
                        subscriptionCertificateInstance.setPublicKey(subscriptionCertificatePublicKeyInstance);
                    }
                    
                    NodeList elements3 = subscriptionCertificatesElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "SubscriptionCertificateThumbprint");
                    Element subscriptionCertificateThumbprintElement = elements3.getLength() > 0 ? ((Element)elements3.item(0)) : null;
                    if (subscriptionCertificateThumbprintElement != null)
                    {
                        String subscriptionCertificateThumbprintInstance;
                        subscriptionCertificateThumbprintInstance = subscriptionCertificateThumbprintElement.getNodeValue();
                        subscriptionCertificateInstance.setThumbprint(subscriptionCertificateThumbprintInstance);
                    }
                    
                    NodeList elements4 = subscriptionCertificatesElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "SubscriptionCertificateData");
                    Element subscriptionCertificateDataElement = elements4.getLength() > 0 ? ((Element)elements4.item(0)) : null;
                    if (subscriptionCertificateDataElement != null)
                    {
                        byte[] subscriptionCertificateDataInstance;
                        subscriptionCertificateDataInstance = Base64.decodeBase64(subscriptionCertificateDataElement.getNodeValue().getBytes());
                        subscriptionCertificateInstance.setData(subscriptionCertificateDataInstance);
                    }
                    
                    NodeList elements5 = subscriptionCertificatesElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "Created");
                    Element createdElement = elements5.getLength() > 0 ? ((Element)elements5.item(0)) : null;
                    if (createdElement != null)
                    {
                        Calendar createdInstance;
                        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("EEE MMM dd HH:mm:ss z yyyy");
                        Calendar calendar = Calendar.getInstance();
                        calendar.setTime(simpleDateFormat.parse(createdElement.getNodeValue()));
                        createdInstance = calendar;
                        subscriptionCertificateInstance.setCreated(createdInstance);
                    }
                }
            }
            
            return result;
        }
        finally
        {
            if (httpClient != null)
            {
                httpClient.close();
            }
        }
    }
}
