// 
// Copyright (c) Microsoft.  All rights reserved.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//   http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// 
// See the License for the specific language governing permissions and
// limitations under the License.
// 

// Warning: This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if the
// code is regenerated.

package com.microsoft.windowsazure.management;

import com.microsoft.windowsazure.OperationResponse;
import com.microsoft.windowsazure.common.CloudException;
import com.microsoft.windowsazure.common.IServiceOperations;
import com.microsoft.windowsazure.management.ISubscriptionOperations;
import com.microsoft.windowsazure.management.ManagementClient;
import com.microsoft.windowsazure.management.models.SubscriptionGetResponse;
import com.microsoft.windowsazure.management.models.SubscriptionListOperationsParameters;
import com.microsoft.windowsazure.management.models.SubscriptionListOperationsResponse;
import com.microsoft.windowsazure.management.models.SubscriptionListOperationsResponse.OperationCallerDetails;
import com.microsoft.windowsazure.management.models.SubscriptionListOperationsResponse.SubscriptionOperation;
import com.microsoft.windowsazure.management.models.SubscriptionStatus;
import java.lang.NullPointerException;
import java.util.Date;
import java.util.concurrent.Future;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import org.apache.http.HttpResponse;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.client.methods.HttpPut;
import org.apache.http.impl.nio.client.CloseableHttpAsyncClient;
import org.apache.http.impl.nio.client.HttpAsyncClients;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;

/**
* Operation for listing subscription operations and details.  (see
* http://msdn.microsoft.com/en-us/library/windowsazure/gg715315.aspx for more
* information)
*/
class SubscriptionOperations extends IServiceOperations<ManagementClient> implements ISubscriptionOperations
{
    /**
    * Initializes a new instance of the SubscriptionOperations class.
    *
    * @param client Reference to the service client.
    */
    SubscriptionOperations(ManagementClient client)
    {
        this._client = client;
    }
    
    private ManagementClient _client;
    
    /**
    * Gets a reference to the
    * microsoft.windowsazure.management.ManagementClient.
    */
    public ManagementClient getClient() { return this._client; }
    
    /**
    * The Get Subscription operation returns account and resource allocation
    * information on the specified subscription.  (see
    * http://msdn.microsoft.com/en-us/library/windowsazure/hh403995.aspx for
    * more information)
    *
    * @return The Get Subscription operation response.
    */
    public SubscriptionGetResponse GetAsync()
    {
        // Validate
        
        // Tracing
        
        // Construct URL
        String url = this.getClient().getBaseUri() + "/" + this.getClient().getCredentials().getSubscriptionId();
        
        // Create HTTP transport objects
        CloseableHttpAsyncClient httpClient = HttpAsyncClients.createDefault();
        try
        {
            httpClient.start();
            HttpGet httpRequest = new HttpGet(url);
            
            // Set Headers
            httpRequest.setRequestProperty("x-ms-version", "2013-03-01");
            
            // Set Credentials
            
            // Send Request
            HttpResponse httpResponse = null;
            Future<HttpResponse> httpRequestFuture = httpClient.execute(httpRequest);
            httpResponse = httpRequestFuture.get();
            int statusCode = httpResponse.getStatusLine().getStatusCode();
            if (statusCode != 200)
            {
                CloudException ex = CloudException.createFromXml(httpRequest, null, httpResponse, httpResponse.getEntity().getContent());
                throw ex;
            }
            
            // Create Result
            SubscriptionGetResponse result = new SubscriptionGetResponse();
            result.setStatusCode(statusCode);
            if (httpResponse.getHeaders("x-ms-request-id").getlength() > 0)
            {
                result.setRequestId(httpResponse.getHeaders("x-ms-request-id")[0]);
            }
            
            // Deserialize Response
            String responseContent = httpResponse.getEntity().getContent();
            DocumentBuilderFactory documentBuilderFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder documentBuilder = documentBuilderFactory.newDocumentBuilder();
            Document responseDoc = documentBuilder.parse(responseContent);
            
            NodeList elements = responseDoc.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "Subscription");
            Element subscriptionElement = elements.getLength() > 0 ? (Element)elements.item(0) : null;
            if (subscriptionElement != null)
            {
                NodeList elements2 = subscriptionElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "SubscriptionID");
                Element subscriptionIDElement = elements2.getLength() > 0 ? (Element)elements2.item(0) : null;
                if (subscriptionIDElement != null)
                {
                    String subscriptionIDInstance;
                    subscriptionIDInstance = subscriptionIDElement.getNodeValue();
                    result.setSubscriptionID(subscriptionIDInstance);
                }
                
                NodeList elements3 = subscriptionElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "SubscriptionName");
                Element subscriptionNameElement = elements3.getLength() > 0 ? (Element)elements3.item(0) : null;
                if (subscriptionNameElement != null)
                {
                    String subscriptionNameInstance;
                    subscriptionNameInstance = subscriptionNameElement.getNodeValue();
                    result.setSubscriptionName(subscriptionNameInstance);
                }
                
                NodeList elements4 = subscriptionElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "SubscriptionStatus");
                Element subscriptionStatusElement = elements4.getLength() > 0 ? (Element)elements4.item(0) : null;
                if (subscriptionStatusElement != null)
                {
                    SubscriptionStatus subscriptionStatusInstance;
                    subscriptionStatusInstance = SubscriptionStatus.valueOf(subscriptionStatusElement.getNodeValue());
                    result.setSubscriptionStatus(subscriptionStatusInstance);
                }
                
                NodeList elements5 = subscriptionElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "AccountAdminLiveEmailId");
                Element accountAdminLiveEmailIdElement = elements5.getLength() > 0 ? (Element)elements5.item(0) : null;
                if (accountAdminLiveEmailIdElement != null)
                {
                    String accountAdminLiveEmailIdInstance;
                    accountAdminLiveEmailIdInstance = accountAdminLiveEmailIdElement.getNodeValue();
                    result.setAccountAdminLiveEmailId(accountAdminLiveEmailIdInstance);
                }
                
                NodeList elements6 = subscriptionElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "ServiceAdminLiveEmailId");
                Element serviceAdminLiveEmailIdElement = elements6.getLength() > 0 ? (Element)elements6.item(0) : null;
                if (serviceAdminLiveEmailIdElement != null)
                {
                    String serviceAdminLiveEmailIdInstance;
                    serviceAdminLiveEmailIdInstance = serviceAdminLiveEmailIdElement.getNodeValue();
                    result.setServiceAdminLiveEmailId(serviceAdminLiveEmailIdInstance);
                }
                
                NodeList elements7 = subscriptionElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "MaxCoreCount");
                Element maxCoreCountElement = elements7.getLength() > 0 ? (Element)elements7.item(0) : null;
                if (maxCoreCountElement != null)
                {
                    int maxCoreCountInstance;
                    maxCoreCountInstance = int.parseInt(maxCoreCountElement.getNodeValue());
                    result.setMaximumCoreCount(maxCoreCountInstance);
                }
                
                NodeList elements8 = subscriptionElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "MaxStorageAccounts");
                Element maxStorageAccountsElement = elements8.getLength() > 0 ? (Element)elements8.item(0) : null;
                if (maxStorageAccountsElement != null)
                {
                    int maxStorageAccountsInstance;
                    maxStorageAccountsInstance = int.parseInt(maxStorageAccountsElement.getNodeValue());
                    result.setMaximumStorageAccounts(maxStorageAccountsInstance);
                }
                
                NodeList elements9 = subscriptionElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "MaxHostedServices");
                Element maxHostedServicesElement = elements9.getLength() > 0 ? (Element)elements9.item(0) : null;
                if (maxHostedServicesElement != null)
                {
                    int maxHostedServicesInstance;
                    maxHostedServicesInstance = int.parseInt(maxHostedServicesElement.getNodeValue());
                    result.setMaximumHostedServices(maxHostedServicesInstance);
                }
                
                NodeList elements10 = subscriptionElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "CurrentCoreCount");
                Element currentCoreCountElement = elements10.getLength() > 0 ? (Element)elements10.item(0) : null;
                if (currentCoreCountElement != null)
                {
                    int currentCoreCountInstance;
                    currentCoreCountInstance = int.parseInt(currentCoreCountElement.getNodeValue());
                    result.setCurrentCoreCount(currentCoreCountInstance);
                }
                
                NodeList elements11 = subscriptionElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "CurrentStorageAccounts");
                Element currentStorageAccountsElement = elements11.getLength() > 0 ? (Element)elements11.item(0) : null;
                if (currentStorageAccountsElement != null)
                {
                    int currentStorageAccountsInstance;
                    currentStorageAccountsInstance = int.parseInt(currentStorageAccountsElement.getNodeValue());
                    result.setCurrentStorageAccounts(currentStorageAccountsInstance);
                }
                
                NodeList elements12 = subscriptionElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "CurrentHostedServices");
                Element currentHostedServicesElement = elements12.getLength() > 0 ? (Element)elements12.item(0) : null;
                if (currentHostedServicesElement != null)
                {
                    int currentHostedServicesInstance;
                    currentHostedServicesInstance = int.parseInt(currentHostedServicesElement.getNodeValue());
                    result.setCurrentHostedServices(currentHostedServicesInstance);
                }
                
                NodeList elements13 = subscriptionElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "MaxVirtualNetworkSites");
                Element maxVirtualNetworkSitesElement = elements13.getLength() > 0 ? (Element)elements13.item(0) : null;
                if (maxVirtualNetworkSitesElement != null)
                {
                    int maxVirtualNetworkSitesInstance;
                    maxVirtualNetworkSitesInstance = int.parseInt(maxVirtualNetworkSitesElement.getNodeValue());
                    result.setMaximumVirtualNetworkSites(maxVirtualNetworkSitesInstance);
                }
                
                NodeList elements14 = subscriptionElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "CurrentVirtualNetworkSites");
                Element currentVirtualNetworkSitesElement = elements14.getLength() > 0 ? (Element)elements14.item(0) : null;
                if (currentVirtualNetworkSitesElement != null)
                {
                    int currentVirtualNetworkSitesInstance;
                    currentVirtualNetworkSitesInstance = int.parseInt(currentVirtualNetworkSitesElement.getNodeValue());
                    result.setCurrentVirtualNetworkSites(currentVirtualNetworkSitesInstance);
                }
                
                NodeList elements15 = subscriptionElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "MaxLocalNetworkSites");
                Element maxLocalNetworkSitesElement = elements15.getLength() > 0 ? (Element)elements15.item(0) : null;
                if (maxLocalNetworkSitesElement != null)
                {
                    int maxLocalNetworkSitesInstance;
                    maxLocalNetworkSitesInstance = int.parseInt(maxLocalNetworkSitesElement.getNodeValue());
                    result.setMaximumLocalNetworkSites(maxLocalNetworkSitesInstance);
                }
                
                NodeList elements16 = subscriptionElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "MaxDnsServers");
                Element maxDnsServersElement = elements16.getLength() > 0 ? (Element)elements16.item(0) : null;
                if (maxDnsServersElement != null)
                {
                    int maxDnsServersInstance;
                    maxDnsServersInstance = int.parseInt(maxDnsServersElement.getNodeValue());
                    result.setMaximumDnsServers(maxDnsServersInstance);
                }
                
                NodeList elements17 = subscriptionElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "CurrentLocalNetworkSites");
                Element currentLocalNetworkSitesElement = elements17.getLength() > 0 ? (Element)elements17.item(0) : null;
                if (currentLocalNetworkSitesElement != null)
                {
                    int currentLocalNetworkSitesInstance;
                    currentLocalNetworkSitesInstance = int.parseInt(currentLocalNetworkSitesElement.getNodeValue());
                    result.setCurrentLocalNetworkSites(currentLocalNetworkSitesInstance);
                }
                
                NodeList elements18 = subscriptionElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "CurrentDnsServers");
                Element currentDnsServersElement = elements18.getLength() > 0 ? (Element)elements18.item(0) : null;
                if (currentDnsServersElement != null)
                {
                    int currentDnsServersInstance;
                    currentDnsServersInstance = int.parseInt(currentDnsServersElement.getNodeValue());
                    result.setCurrentDnsServers(currentDnsServersInstance);
                }
            }
            
            return result;
        }
        finally
        {
            if (httpClient != null)
            {
                httpClient.close();
            }
        }
    }
    
    /**
    * The List Subscription Operations operation returns a list of create,
    * update, and delete operations that were performed on a subscription
    * during the specified timeframe.  (see
    * http://msdn.microsoft.com/en-us/library/windowsazure/gg715318.aspx for
    * more information)
    *
    * @param parameters Parameters supplied to the List Subscription Operations
    * operation.
    * @return The List Subscription Operations operation response.
    */
    public SubscriptionListOperationsResponse ListOperationsAsync(SubscriptionListOperationsParameters parameters)
    {
        // Validate
        if (parameters == null)
        {
            throw new NullPointerException("parameters");
        }
        
        // Tracing
        
        // Construct URL
        String url = this.getClient().getBaseUri() + "/" + this.getClient().getCredentials().getSubscriptionId() + "/operations?";
        url = url + "&StartTime=" + org.apache.commons.httpclient.util.URIUtil.encodeQuery(parameters.getStartTime().ToString("O"));
        url = url + "&EndTime=" + org.apache.commons.httpclient.util.URIUtil.encodeQuery(parameters.getEndTime().ToString("O"));
        if (parameters.getObjectIdFilter() != null)
        {
            url = url + "&ObjectIdFilter=" + org.apache.commons.httpclient.util.URIUtil.encodeQuery(parameters.getObjectIdFilter());
        }
        if (parameters.getOperationStatus() != null)
        {
            url = url + "&OperationResultFilter=" + org.apache.commons.httpclient.util.URIUtil.encodeQuery(parameters.getOperationStatus().getValue().toString());
        }
        if (parameters.getContinuationToken() != null)
        {
            url = url + "&ContinuationToken=" + org.apache.commons.httpclient.util.URIUtil.encodeQuery(parameters.getContinuationToken());
        }
        
        // Create HTTP transport objects
        CloseableHttpAsyncClient httpClient = HttpAsyncClients.createDefault();
        try
        {
            httpClient.start();
            HttpGet httpRequest = new HttpGet(url);
            
            // Set Headers
            httpRequest.setRequestProperty("x-ms-version", "2013-03-01");
            
            // Set Credentials
            
            // Send Request
            HttpResponse httpResponse = null;
            Future<HttpResponse> httpRequestFuture = httpClient.execute(httpRequest);
            httpResponse = httpRequestFuture.get();
            int statusCode = httpResponse.getStatusLine().getStatusCode();
            if (statusCode != 200)
            {
                CloudException ex = CloudException.createFromXml(httpRequest, null, httpResponse, httpResponse.getEntity().getContent());
                throw ex;
            }
            
            // Create Result
            SubscriptionListOperationsResponse result = new SubscriptionListOperationsResponse();
            result.setStatusCode(statusCode);
            if (httpResponse.getHeaders("x-ms-request-id").getlength() > 0)
            {
                result.setRequestId(httpResponse.getHeaders("x-ms-request-id")[0]);
            }
            
            // Deserialize Response
            String responseContent = httpResponse.getEntity().getContent();
            DocumentBuilderFactory documentBuilderFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder documentBuilder = documentBuilderFactory.newDocumentBuilder();
            Document responseDoc = documentBuilder.parse(responseContent);
            
            NodeList elements = responseDoc.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "SubscriptionOperationCollection");
            Element subscriptionOperationCollectionElement = elements.getLength() > 0 ? (Element)elements.item(0) : null;
            if (subscriptionOperationCollectionElement != null)
            {
                NodeList elements2 = subscriptionOperationCollectionElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "ContinuationToken");
                Element continuationTokenElement = elements2.getLength() > 0 ? (Element)elements2.item(0) : null;
                if (continuationTokenElement != null)
                {
                    String continuationTokenInstance;
                    continuationTokenInstance = continuationTokenElement.getNodeValue();
                    result.setContinuationToken(continuationTokenInstance);
                }
                
                NodeList elements3 = subscriptionOperationCollectionElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "SubscriptionOperations");
                Element subscriptionOperationsSequenceElement = elements3.getLength() > 0 ? (Element)elements3.item(0) : null;
                if (subscriptionOperationsSequenceElement != null)
                {
                    for (Element subscriptionOperationsElement : subscriptionOperationsSequenceElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "SubscriptionOperation"))
                    {
                        SubscriptionListOperationsResponse.SubscriptionOperation subscriptionOperationInstance = new SubscriptionListOperationsResponse.SubscriptionOperation();
                        result.getSubscriptionOperations().Add(subscriptionOperationInstance);
                        
                        NodeList elements4 = subscriptionOperationsElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "OperationId");
                        Element operationIdElement = elements4.getLength() > 0 ? (Element)elements4.item(0) : null;
                        if (operationIdElement != null)
                        {
                            String operationIdInstance;
                            operationIdInstance = operationIdElement.getNodeValue();
                            subscriptionOperationInstance.setOperationId(operationIdInstance);
                        }
                        
                        NodeList elements5 = subscriptionOperationsElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "OperationObjectId");
                        Element operationObjectIdElement = elements5.getLength() > 0 ? (Element)elements5.item(0) : null;
                        if (operationObjectIdElement != null)
                        {
                            String operationObjectIdInstance;
                            operationObjectIdInstance = operationObjectIdElement.getNodeValue();
                            subscriptionOperationInstance.setOperationObjectId(operationObjectIdInstance);
                        }
                        
                        NodeList elements6 = subscriptionOperationsElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "OperationName");
                        Element operationNameElement = elements6.getLength() > 0 ? (Element)elements6.item(0) : null;
                        if (operationNameElement != null)
                        {
                            String operationNameInstance;
                            operationNameInstance = operationNameElement.getNodeValue();
                            subscriptionOperationInstance.setOperationName(operationNameInstance);
                        }
                        
                        NodeList elements7 = subscriptionOperationsElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "OperationParameters");
                        Element operationParametersSequenceElement = elements7.getLength() > 0 ? (Element)elements7.item(0) : null;
                        if (operationParametersSequenceElement != null)
                        {
                            for (Element operationParametersElement : operationParametersSequenceElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "OperationParameter"))
                            {
                                NodeList elements8 = operationParametersElement.getElementsByTagNameNS("http://schemas.datacontract.org/2004/07/Microsoft.WindowsAzure.ServiceManagement", "Name");
                                String operationParametersKey = elements8.getLength() > 0 ? (Element)elements8.item(0) : null.getNodeValue();
                                NodeList elements9 = operationParametersElement.getElementsByTagNameNS("http://schemas.datacontract.org/2004/07/Microsoft.WindowsAzure.ServiceManagement", "Value");
                                String operationParametersValue = elements9.getLength() > 0 ? (Element)elements9.item(0) : null.getNodeValue();
                                subscriptionOperationInstance.getOperationParameters().Add(operationParametersKey, operationParametersValue);
                            }
                        }
                        
                        NodeList elements10 = subscriptionOperationsElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "OperationCaller");
                        Element operationCallerElement = elements10.getLength() > 0 ? (Element)elements10.item(0) : null;
                        if (operationCallerElement != null)
                        {
                            SubscriptionListOperationsResponse.OperationCallerDetails operationCallerInstance = new SubscriptionListOperationsResponse.OperationCallerDetails();
                            subscriptionOperationInstance.setOperationCaller(operationCallerInstance);
                            
                            NodeList elements11 = operationCallerElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "UsedServiceManagementApi");
                            Element usedServiceManagementApiElement = elements11.getLength() > 0 ? (Element)elements11.item(0) : null;
                            if (usedServiceManagementApiElement != null)
                            {
                                boolean usedServiceManagementApiInstance;
                                usedServiceManagementApiInstance = boolean.parseBoolean(usedServiceManagementApiElement.getNodeValue());
                                operationCallerInstance.setUsedServiceManagementApi(usedServiceManagementApiInstance);
                            }
                            
                            NodeList elements12 = operationCallerElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "UserEmailAddress");
                            Element userEmailAddressElement = elements12.getLength() > 0 ? (Element)elements12.item(0) : null;
                            if (userEmailAddressElement != null)
                            {
                                String userEmailAddressInstance;
                                userEmailAddressInstance = userEmailAddressElement.getNodeValue();
                                operationCallerInstance.setUserEmailAddress(userEmailAddressInstance);
                            }
                            
                            NodeList elements13 = operationCallerElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "SubscriptionCertificateThumbprint");
                            Element subscriptionCertificateThumbprintElement = elements13.getLength() > 0 ? (Element)elements13.item(0) : null;
                            if (subscriptionCertificateThumbprintElement != null)
                            {
                                String subscriptionCertificateThumbprintInstance;
                                subscriptionCertificateThumbprintInstance = subscriptionCertificateThumbprintElement.getNodeValue();
                                operationCallerInstance.setSubscriptionCertificateThumbprint(subscriptionCertificateThumbprintInstance);
                            }
                            
                            NodeList elements14 = operationCallerElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "ClientIP");
                            Element clientIPElement = elements14.getLength() > 0 ? (Element)elements14.item(0) : null;
                            if (clientIPElement != null)
                            {
                                string clientIPInstance;
                                clientIPInstance = clientIPElement.getNodeValue();
                                operationCallerInstance.setClientIPAddress(clientIPInstance);
                            }
                        }
                        
                        NodeList elements15 = subscriptionOperationsElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "OperationStatus");
                        Element operationStatusElement = elements15.getLength() > 0 ? (Element)elements15.item(0) : null;
                        if (operationStatusElement != null)
                        {
                            String operationStatusInstance;
                            operationStatusInstance = operationStatusElement.getNodeValue();
                            subscriptionOperationInstance.setOperationStatus(operationStatusInstance);
                        }
                        
                        NodeList elements16 = subscriptionOperationsElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "OperationStartedTime");
                        Element operationStartedTimeElement = elements16.getLength() > 0 ? (Element)elements16.item(0) : null;
                        if (operationStartedTimeElement != null)
                        {
                            Date operationStartedTimeInstance;
                            operationStartedTimeInstance = operationStartedTimeElement.getNodeValue();
                            subscriptionOperationInstance.setOperationStartedTime(operationStartedTimeInstance);
                        }
                        
                        NodeList elements17 = subscriptionOperationsElement.getElementsByTagNameNS("http://schemas.microsoft.com/windowsazure", "OperationCompletedTime");
                        Element operationCompletedTimeElement = elements17.getLength() > 0 ? (Element)elements17.item(0) : null;
                        if (operationCompletedTimeElement != null)
                        {
                            Date operationCompletedTimeInstance;
                            operationCompletedTimeInstance = operationCompletedTimeElement.getNodeValue();
                            subscriptionOperationInstance.setOperationCompletedTime(operationCompletedTimeInstance);
                        }
                    }
                }
            }
            
            return result;
        }
        finally
        {
            if (httpClient != null)
            {
                httpClient.close();
            }
        }
    }
    
    /**
    * Register a resource with your subscription.
    *
    * @param resourceName Name of the resource to register.
    * @return A standard service response including an HTTP status code and
    * request ID.
    */
    public OperationResponse RegisterResourceAsync(String resourceName)
    {
        // Validate
        if (resourceName == null)
        {
            throw new NullPointerException("resourceName");
        }
        
        // Tracing
        
        // Construct URL
        String url = this.getClient().getBaseUri() + "/" + this.getClient().getCredentials().getSubscriptionId() + "/services?service=" + resourceName + "&action=register";
        
        // Create HTTP transport objects
        CloseableHttpAsyncClient httpClient = HttpAsyncClients.createDefault();
        try
        {
            httpClient.start();
            HttpPut httpRequest = new HttpPut(url);
            
            // Set Headers
            httpRequest.setRequestProperty("Content-Type", "application/xml");
            httpRequest.setRequestProperty("x-ms-version", "2013-03-01");
            
            // Set Credentials
            
            // Send Request
            HttpResponse httpResponse = null;
            Future<HttpResponse> httpRequestFuture = httpClient.execute(httpRequest);
            httpResponse = httpRequestFuture.get();
            int statusCode = httpResponse.getStatusLine().getStatusCode();
            if (statusCode != 200 && statusCode != 202)
            {
                CloudException ex = CloudException.createFromXml(httpRequest, null, httpResponse, httpResponse.getEntity().getContent());
                throw ex;
            }
            
            // Create Result
            OperationResponse result = new OperationResponse();
            result.setStatusCode(statusCode);
            if (httpResponse.getHeaders("x-ms-request-id").getlength() > 0)
            {
                result.setRequestId(httpResponse.getHeaders("x-ms-request-id")[0]);
            }
            
            return result;
        }
        finally
        {
            if (httpClient != null)
            {
                httpClient.close();
            }
        }
    }
    
    /**
    * Unregister a resource with your subscription.
    *
    * @param resourceName Name of the resource to unregister.
    * @return A standard service response including an HTTP status code and
    * request ID.
    */
    public OperationResponse UnregisterResourceAsync(String resourceName)
    {
        // Validate
        if (resourceName == null)
        {
            throw new NullPointerException("resourceName");
        }
        
        // Tracing
        
        // Construct URL
        String url = this.getClient().getBaseUri() + "/" + this.getClient().getCredentials().getSubscriptionId() + "/services?service=" + resourceName + "&action=unregister";
        
        // Create HTTP transport objects
        CloseableHttpAsyncClient httpClient = HttpAsyncClients.createDefault();
        try
        {
            httpClient.start();
            HttpPut httpRequest = new HttpPut(url);
            
            // Set Headers
            httpRequest.setRequestProperty("Content-Type", "application/xml");
            httpRequest.setRequestProperty("x-ms-version", "2013-03-01");
            
            // Set Credentials
            
            // Send Request
            HttpResponse httpResponse = null;
            Future<HttpResponse> httpRequestFuture = httpClient.execute(httpRequest);
            httpResponse = httpRequestFuture.get();
            int statusCode = httpResponse.getStatusLine().getStatusCode();
            if (statusCode != 200 && statusCode != 202)
            {
                CloudException ex = CloudException.createFromXml(httpRequest, null, httpResponse, httpResponse.getEntity().getContent());
                throw ex;
            }
            
            // Create Result
            OperationResponse result = new OperationResponse();
            result.setStatusCode(statusCode);
            if (httpResponse.getHeaders("x-ms-request-id").getlength() > 0)
            {
                result.setRequestId(httpResponse.getHeaders("x-ms-request-id")[0]);
            }
            
            return result;
        }
        finally
        {
            if (httpClient != null)
            {
                httpClient.close();
            }
        }
    }
}
